spring:
  application:
    name: ms-inventory

  data:
    mongodb:
      uri: mongodb://192.168.100.81:27017/ecommerce

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080
