apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-inventory
  namespace: {{.Values.saga_pattern.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-inventory
  template:
    metadata:
      labels:
        app: ms-inventory
    spec:
      containers:
        - name: ms-inventory
          image: "{{ .Values.saga_pattern.images.registry }}/ms-inventory:{{ .Values.saga_pattern.images.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_DATA_MONGODB_URI
              value: {{ .Values.saga_pattern.db.mongo_uri }}
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.saga_pattern.kafka.bootstrap_servers }}
---
apiVersion: v1
kind: Service
metadata:
  name: ms-inventory-svc
  namespace: {{.Values.saga_pattern.namespace }}
spec:
  selector:
    app: ms-inventory
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
