apiVersion: apps/v1
kind: Deployment
metadata:
  name: saga-orchestrator
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saga-orchestrator
  template:
    metadata:
      labels:
        app: saga-orchestrator
    spec:
      containers:
        - name: saga-orchestrator
          image: my-ecommerce/saga-orchestrator:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: saga-orchestrator
  namespace: ecommerce
spec:
  selector:
    app: saga-orchestrator
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
